export enum CalculatorActionsType {
  LOAD_CALCULATOR = "LOAD_CALCULATOR",
  RENDER_CALCULATOR = "RENDER_CALCULATOR",
  RESET_CALCULATOR = "RESET_CALCULATOR",
  MAKE_CALC = "MAKE_CALC",
  SET_MONTHLY_INGREDIENT_SPENDING = "SET_MONTHLY_INGREDIENT_SPENDING",
  SET_FULL_TIME_EMPLOYEE = "SET_FULL_TIME_EMPLOYEE"
}
