export enum TestimonialActionsType {
  LOAD_TESTIMONIAL = "LOAD_TESTIMONIAL",
  RENDER_TESTIMONIAL = "RENDER_SLIDER",
  RESET_TESTIMONIAL = "RESET_TESTIMONIAL",
  NEXT_CARD = "NEXT_CARD",
  PREV_CARD = "PREV_CARD"
}
